### PR TITLE
Fix unmapped icon handlement

### LINKED ISSUE #610: Unknown icon names can break unit tests
We have seen cases where unit tests will break with `Icon(...): Nothing was returned from render. This usually means a return statement is missing. Or, to render nothing, return null.`.  This is caused by improperly named icons, such as `<Icon name='moon' />` instead of `<Icon name='Overnight' />`

This issue was introduced at some point after pcln-design-system 2.3.2

### PR DESCRIPTION
**Pull request by BeniCheni**
Fixes #610 

Plus rearrange to use less default props for html attributes that could be inline in JSX.

##### Test to validate all existing a11y attributes and retain working icon feature

Screen Shot 2019-10-11 at 5 08 15 PM

### CODE REVIEW

File: packages/icons/src/Icon.js [hunk 1]
```diff
@@ -10,29 +10,35 @@ const Icon = ({ name, title, desc, titleId, descId, ...props }) => {
...
-        aria-labelledby={ariaLabelledBy}
-        {...props}
-      />
+  if (!Component) {
+    if (process.env.NODE_ENV !== 'production')
+      console.trace(`icon ${iconName} does not exist`)
+    return null
+  } else {
+    return (
+      Component && (
```
Comment (jes708) [inline packages/icons/src/Icon.js]: This check `Component && ` shouldn't be necessary anymore, since we know from the conditional that Component does exist.

File: packages/icons/src/Icon.js [hunk 2]
```diff
@@ -10,29 +10,35 @@ const Icon = ({ name, title, desc, titleId, descId, ...props }) => {
...
+        <Component
+          aria-hidden="true"
+          title={title}
+          desc={desc}
+          titleId={titleId}
+          descId={descId}
+          aria-hidden={!!ariaLabelledBy || true}
+          aria-labelledby={ariaLabelledBy}
+          tabIndex={-1}
+          focusable={false}
```
Comment (jes708) [inline packages/icons/src/Icon.js]: I think this might need to be focusable='false', but if you're seeing it correctly in the DOM, then I'll stand corrected :)

**Comment by jes708** [comment]
packages/icons/src/Svg.js also contains the defaultProps you adjusted, so I think an update is needed there too.

File: packages/icons/src/Icon.js (hunk 2 above)
Comment (BeniCheni) [reply packages/icons/src/Icon.js]: I think React suggests to use JavaScript convention like (-1 as a number for tableIdex, which is also camel cased by React, and then these `false` / `true` value)

File: packages/icons/src/Icon.js [hunk 3]
```diff
@@ -10,29 +10,33 @@ const Icon = ({ name, title, desc, titleId, descId, ...props }) => {
...
+  } else {
+    return (
       <Component
+        aria-hidden="true"
         title={title}
         desc={desc}
         titleId={titleId}
         descId={descId}
-        aria-hidden={!!ariaLabelledBy}
+        aria-hidden={!!ariaLabelledBy || true}
```
Comment (jes708) [inline packages/icons/src/Icon.js]: looks like aria-hidden is specified twice in this Component

File: packages/icons/src/Icon.js (hunk 1 above)
Comment (BeniCheni) [reply packages/icons/src/Icon.js]: @jes708 , good 👁 , updated.

File: packages/icons/src/Icon.js [hunk 4]
```diff
@@ -10,29 +10,33 @@ const Icon = ({ name, title, desc, titleId, descId, ...props }) => {
...
-  return (
-    Component && (
+  if (!Component) {
+    if (process.env.NODE_ENV !== 'production')
+      console.trace(`icon ${iconName} does not exist`)
+    return null
+  } else {
+    return (
       <Component
+        aria-hidden="true"
```
Comment (jes708) [inline packages/icons/src/Icon.js]: Here is the first aria-hidden

File: packages/icons/src/Icon.js (hunk 3 above)
Comment (BeniCheni) [reply packages/icons/src/Icon.js]: @jes708, only once... I've deleted the aria-hidden from default props, and use it as a default case here.

The thought behind it is to use less default props with weird object key quoting like 'aria-hidden', and use the aria-hidden = true as a fault back value by `||` operator, when aria labelled by value is not valid.

File: packages/icons/src/Icon.js (hunk 4 above)
Comment (BeniCheni) [reply packages/icons/src/Icon.js]: Ah, yeah. Removed it.

**Comment by BeniCheni** [comment]
> packages/icons/src/Svg.js also contains the defaultProps you adjusted, so I think an update is needed there too.

@jes708, looks like the latest in master corrected these already:

https://github.com/pricelinelabs/design-system/blob/39beb570538f22489424b2f3ce355dc7c7cd8b37/packages/icons/svgr.config.js#L32-L34

File: packages/icons/src/Icon.js [hunk 5]
```diff
@@ -10,29 +10,32 @@ const Icon = ({ name, title, desc, titleId, descId, ...props }) => {
...
+    return null
+  } else {
+    return (
       <Component
         title={title}
         desc={desc}
         titleId={titleId}
         descId={descId}
-        aria-hidden={!!ariaLabelledBy}
+        aria-hidden={!!ariaLabelledBy || true}
```
Comment (James300) [inline packages/icons/src/Icon.js]: Do you think it would make more sense to change `undefined` on line 11 to true?

Comment (sdalonzo) [reply packages/icons/src/Icon.js]: yea, this seems incorrect. `X || true` is always truthy, and `!!` already coerced `ariaLabelledBy` to bool

**Comment by sdalonzo** [comment]
> > packages/icons/src/Svg.js also contains the defaultProps you adjusted, so I think an update is needed there too.
> 
> @jes708, looks like the latest in master corrected these already:
> 
> https://github.com/pricelinelabs/design-system/blob/39beb570538f22489424b2f3ce355dc7c7cd8b37/packages/icons/svgr.config.js#L32-L34

i think @jes708 is saying that since they are now inline in the JSX, the svgr config doesn't need them since they aren't props

File: packages/icons/src/Icon.js (hunk 5 above)
Comment (BeniCheni) [reply packages/icons/src/Icon.js]: @James300 / @sdalonzo,
 
Think there's a misunderstanding. At least here what I understood, which could be an overlook. Seems that the current version is correct logic to generate HTML attribute `aria-hidden="true"`, if `ariaLabelledBy` is invalid. Otherwise, `aria-hidden="desc-id-value"`.

Confirmed the logic w. @dgiraldo313 when doing the PR to ensure the a11y requirement. (ping @dgiraldo313 to review the PR, and chime in if he has any thoughts on this logic. Let me know, if I misunderstood your comments. Happy to colla. to get to the bottom of this thread.

Here's the logic from my interpretation.

1) `ariaLabelledBy` variant is determined by`titleId`, `desc` & `descId`. If any of those doesn't validate the rules, default value `undefined` is assigned to `ariaLabelledBy` variant:

https://github.com/pricelinelabs/design-system/blob/39beb570538f22489424b2f3ce355dc7c7cd8b37/packages/icons/src/Icon.js#L9-L11

2. In this update, the PR removed the default prop `aria-hidden: true`, and apply as fall-back default value `true`, if `ariaLabelledBy` from step 1 is ever invalid w. the intentional `undefined` value. This works because `!!undefined || true` => `false || true` => `true` => generate HTML attribute `aria-hidden="true"`.

    If there's a valid `ariaLabelledBy` value, the logic would be `!!'desc-id' || true` => generate HTML attribute `aria-hidden="desc-id"` for valid a11y.

```jsx
aria-hidden={!!ariaLabelledBy || true}
```

**Comment by BeniCheni** [comment]
> i think @jes708 is saying that since they are now inline in the JSX, the svgr config doesn't need them since they aren't props

@sdalonzo, spoke to @jes708 offline before his LGTM about the svgr config. His comment was wondering if the HTML attribute values should be all string quoted, such as `'aria-hidden': 'true',` instead, which was a version before the previous previous before the PR. It seems a confusing thread, but we agreed that for React syntax (similar to camel case instead of the normal HTML attributes in lower case), these HTML attribute values could use JavaScript instead of string quoting.

Per your thought about revoming, I tried it out locally and the Icon unit tests started to fail. I wouldn't want to take too much risk. The currently inline attributes over in `Icon` was to replace its own default prop values, but the scope doesn't seem to cover svgr config.

(If you'd like, you can pull the branch of `unkown-icon-handlement` and try removing and see if any tests fail? Maybe colla on a follow PR, while this PR can move forward to fix the unmapped `name` prop in `Icon`.)

**Comment by BeniCheni** [comment]
> mind using curly braces here? this one is a little tricky to read.

@sdalonzo, 😸 why not. [27bc50d](https://github.com/pricelinelabs/design-system/pull/615/commits/27bc50d78e5cafd5ea4826b7ad04c442073c68a9) updated.

File: packages/icons/src/Icon.js (hunk 5 above)
Comment (sdalonzo) [reply packages/icons/src/Icon.js]: @BeniCheni except that the `!!` already coerced the `aria-labelled-by` to a bool:

image

**Comment by BeniCheni** [comment]
> yea, this seems incorrect. X || true is always truthy, and !! already coerced ariaLabelledBy to bool

@sdalonzo, nice 🎣 Updated the aria-hidden logic to do something along the line such as: `'desc-id' || true`. PTAL?

File: packages/icons/src/Icon.js [hunk 6]
```diff
@@ -10,29 +10,33 @@ const Icon = ({ name, title, desc, titleId, descId, ...props }) => {
...
+    return null
+  } else {
+    return (
       <Component
         title={title}
         desc={desc}
         titleId={titleId}
         descId={descId}
-        aria-hidden={!!ariaLabelledBy}
+        aria-hidden={Boolean(ariaLabelledBy)}
```
Comment (jes708) [inline packages/icons/src/Icon.js]: Actually, this logic seems backwards to me.  Shouldn't it be `aria-hidden={!ariaLabelledBy}?`  If there is a label, hidden should be false, because we want the user to find the icon and have its label read by the screen reader.  Otherwise, if there is no label, do hide it as there is nothing for the screen reader to say

**Comment by BeniCheni** [comment]
> Approving in anticipation of the discussed !ariaLabelledBy fix

@jes708 , updated to have final version `aria-hidden={!ariaLabelledBy}`.
